// cards-react/src/App.js
import './App.css';

import Card from './components/card/card.component';

const posts = [
  {
    title: 'Neat Tree',
    imageUrl: 'tree.jpeg',
    userName: 'nature',
    content: 'I saw this tree today',
  },
  {
    title: 'Snowy Mountain',
    imageUrl: 'mountain.jpeg',
    userName: 'mountainlover',
    content: 'Here is a pictureof a snowy mountain',
  },
  {
    title: 'Mountatin Biking',
    imageUrl: 'biking.jpeg',
    userName: 'biking12222',
    content: 'I did some biking today',
  },
];

function App() {
  return (
    <div className="App">
      {
        posts.map(({title, imageUrl, userName, content}) => (
          <Card
            key={title}
            title={title}
            imageUrl={imageUrl}
            userName={userName}
            content={content}
          />
        ))
      }
    </div>
  );
}

export default App;

// cards-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  posts = [
    { 
      title: 'Neat Tree',
      imageUrl: 'assets/tree.jpeg', 
      userName: 'nature',
      content: 'I saw this tree today', 
    },
    { 
      title: 'Snowy Mountain',
      imageUrl: 'assets/mountain.jpeg', 
      userName: 'mountainlover',
      content: 'Here is a pictureof a snowy mountain', 
    },
    { 
      title: 'Mountatin Biking',
      imageUrl: 'assets/biking.jpeg', 
      userName: 'biking12222',
      content: 'I did some biking today', 
    },
  ];
}

<app-card></app-card>
<app-card></app-card>
<app-card></app-card>

<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <img src="assets/tree.jpeg" alt="tree" />
    </figure>
  </div>

  <div class="card-content">
    <div class="media-content">
      <p class="title is-4">Neat tree</p>
      <p class="subtitle is-6">@nature</p>
    </div>
    <div class="content">
      Saw this awesome tree during my hike today.
    </div>
  </div>
</div>
