// typing-react/src/App.js
import './App.css';
import { lorem } from 'faker';

const sentence = lorem.sentence();

const handleUserInput = (event) => {
  console.log(event.target.value);
};

function App() {
  return (
    <div className="container">
      <div className="columns is-centered">
        <div className="box column is-one-third">
          <h1 className="title has-text-centered">Typing challenge</h1>

          <p className="has-text-centered">
            { sentence }
          </p>

          <div className="field">
            <input onInput={handleUserInput} className="input" type="text" />
          </div>

          <div className="box has-text-centered">
            <h2 className="title">You win</h2>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// typing-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { lorem } from 'faker';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  sentence = lorem.sentence();

  handleUserInput(value: string) {
    console.log(value);
  }
}

<div class="container">
  <div class="columns is-centered">
    <div class="box column is-one-third">
      <h1 class="title has-text-centered">Typing challenge</h1>

      <p class="has-text-centered">
        {{ sentence }}
      </p>
      
      <div class="field">
        <input (input)="handleUserInput($event.target.value)" class="input" type="text" />
      </div>
      
      <div class="box has-text-centered">
        <h2 class="title">You win</h2>
      </div>
    </div>
  </div>
</div>
